### ISSUE TITLE
How to use other models in this dataset?

### ISSUE THREAD

**Issue by Lordaduss** [piresramon/gpt-4-enem#8]
I'm struggling to test this dataset with other models such as LLAMA. You said you can use any model from the huggin face transformers but I can't figure out where to get the "model" and "model_args" parameters. What would they look like?

If you go to the [ Llama page ](https://huggingface.co/meta-llama/Meta-Llama-3-8B) and click in "Use in Transformers" you get this: 
`# Load model directly
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B")
model = AutoModelForCausalLM.from_pretrained("meta-llama/Meta-Llama-3-8B")`

So I tried using "model = meta-llama" and "model_args = Meta-Llama-3-8B" but that doesn't work.
Like so:
`!python main.py \
--model meta-llama \
--model_args Meta-Llama-3-8B \
--tasks enem_cot_2022_blind,enem_cot_2022_captions \
--description_dict_path description.json \
--num_fewshot 3 \`

I get:
`Selected Tasks: ['enem_cot_2022_blind', 'enem_cot_2022_captions']
Traceback (most recent call last):
  File "/content/gpt-4-enem/main.py", line 112, in <module>
    main()
  File "/content/gpt-4-enem/main.py", line 81, in main
    results = evaluator.simple_evaluate(
  File "/content/gpt-4-enem/lm_eval/utils.py", line 164, in _wrapper
    return fn(*args, **kwargs)
  File "/content/gpt-4-enem/lm_eval/evaluator.py", line 66, in simple_evaluate
    lm = lm_eval.models.get_model(model).create_from_arg_string(
  File "/content/gpt-4-enem/lm_eval/models/__init__.py", line 16, in get_model
    return MODEL_REGISTRY[model_name]
KeyError: 'meta-llama'`

Any help would be appreciated

**Comment by piresramon** [comment]
Hi @Lordaduss. To use any decoder-only model via transformers library, please use `gpt2` as model, and include those parameters (defined in [init function](https://github.com/piresramon/gpt-4-enem/blob/main/lm_eval/models/gpt2.py#L7)) as model_args.

Other small change you must do to run llama models is adding the tokenizer in [this assert](https://github.com/piresramon/gpt-4-enem/blob/main/lm_eval/models/gpt2.py#L53). Or just comment this part of the code.

Probably you will use:

```
python main.py \
  --model gpt2 \
  --model_args pretrained=meta-llama/Meta-Llama-3-8B \
  ...
```

If you have any error, try downgrading the transformer versions (latest versions had changes related to stopping criteria).

**Comment by Lordaduss** [comment]
> Hi @Lordaduss. To use any decoder-only model via transformers library, please use `gpt2` as model, and include those parameters (defined in [init function](https://github.com/piresramon/gpt-4-enem/blob/main/lm_eval/models/gpt2.py#L7)) as model_args.
> 
> Other small change you must do to run llama models is adding the tokenizer in [this assert](https://github.com/piresramon/gpt-4-enem/blob/main/lm_eval/models/gpt2.py#L53). Or just comment this part of the code.
> 
> Probably you will use:
> 
> ```
> python main.py \
>   --model gpt2 \
>   --model_args pretrained=meta-llama/Meta-Llama-3-8B \
>   ...
> ```
> 
> If you have any error, try downgrading the transformer versions (latest versions had changes related to stopping criteria).

Thanks for the reply. Pardon me if I'm slow but can you explain how to add the tokenizer? I think it is working now, I ran it with no errors but without the tokenizer part you said
```
from transformers import AutoTokenizer, AutoModelForCausalLM

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B")
```
I see this code in hugging face but which part do I need to add to your code?

Also, in which file can I see the results? Again sorry if I am dumb

**Comment by piresramon** [comment]
Hi @Lordaduss.
No problem. Probably just adding `transformers.PreTrainedTokenizerFast` [here](https://github.com/piresramon/gpt-4-enem/blob/main/lm_eval/models/gpt2.py#L56) will be enough.
If you have the error below, just comment the lines 50 to 58.
```
this tokenizer has not been checked for compatibility yet!
```

After this, just run the main,py script using `--model gpt2  --model_args pretrained=meta-llama/Meta-Llama-3-8B`.
Let me know if this solved the problem.

Bests,

**Comment by Lordaduss** [comment]
Thank you, it's running. Now the only thing I don't know is, how to see the results?
In collab this is what I see after it's done running:
```
model-00004-of-00004.safetensors:  96% 1.12G/1.17G [00:06<00:00, 183MB/s]
model-00004-of-00004.safetensors: 100% 1.17G/1.17G [00:06<00:00, 185MB/s]
Downloading shards: 100% 4/4 [02:19<00:00, 34.94s/it]
Loading checkpoint shards:  25% 1/4 [00:33<01:39, 33.19s/it]
```
It ends at 25% 1/4 so is it even finishing properly?

**Comment by piresramon** [comment]
Hi @Lordaduss. Sorry for the delay.
The checkpoint was not loaded completely. Probably you are using a machine that does not have enough memory. Can you try with other GPU with more memory?

**Comment by piresramon** [comment]
If you just want to check if the code is working as expected, and do not have GPU, you can test with a very tiny model (e.g., gpt2) locally:

`--model gpt2  --model_args pretrained=gpt2,device=cpu`

**Comment by Lordaduss** [comment]
Damn I guess colab isn't good enough to run it then, and my own GPU is old so I don't think I'll be able to run it. A shame because I wanted to follow up on your work and test with other LLMs as well. But thank you so much for your attention!
